### PR TITLE
refactor: upgrade code to match versions of dependencies

### PR DESCRIPTION
**Pull request by kmdrGroch**

### CODE REVIEW

**Comment by kmdrGroch** [comment]
Breaking changes -> requires ``node >= 6``

**Comment by simondel** [comment]
Looks good! Could you update the node_js versions in .travis.yml like they are the main stryker repo?

**Comment by kmdrGroch** [comment]
@simondel Done :)

**Comment by simondel** [comment]
Thanks for the hard work <3 Do you want to have a video chat sometime this week to get to know each other a bit? You've been helping us for a while now but we don't really know each other yet :)

**Comment by kmdrGroch** [comment]
hm... I think i should have camera in my notebook, but i havent used it / configured. But honestly, why not. Whenever you have time :)

**Comment by simondel** [comment]
Awesome :) What timezone do you live in?

**Comment by kmdrGroch** [comment]
+1

**Comment by simondel** [comment]
Alright! Do you have a preference for a day/time? Calling during office hours is no issue for me, except for monday.

**Comment by kmdrGroch** [comment]
Im at home at 3:30pm everyday

**Comment by simondel** [comment]
@nicojs would you have time to join us this friday? I can make some time before our team's maintenance starts at 16:30.

**Comment by nicojs** [comment]
Sounds great 👍 . I'm available all day. Use https://appear.in/stryker-mutator ?

**Comment by nicojs** [comment]
We're waiting for you @kmdrGroch

**Comment by kmdrGroch** [comment]
@nicojs should i join https://appear.in/stryker-mutator?

**Comment by nicojs** [comment]
Please do :)

**Pull request merged**
